version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # If you need a database in the future, you can uncomment and configure this section
  # db:
  #   image: postgres:13
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=narraflow
  #     - POSTGRES_USER=narraflow
  #     - POSTGRES_PASSWORD=narraflow_password

volumes:
  postgres_data:
