version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # If you need a database in the future, you can uncomment and configure this section
  # db:
  #   image: postgres:13
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=narraflow
  #     - POSTGRES_USER=narraflow
  #     - POSTGRES_PASSWORD=narraflow_password

  #   minio:
  #     image: minio/minio
  #     ports:
  #       - "9000:9000"
  #       - "9001:9001"
  #     volumes:
  #       - minio_data:/data
  #     environment:
  #       - MINIO_ROOT_USER=minio_access_key
  #       - MINIO_ROOT_PASSWORD=minio_secret_key
  #     command: server --console-address ":9001" /data

  #   app:
  #     environment:
  #       - ELEVENLABS_API_KEY=your_api_key_here
  #       - MINIO_ENDPOINT=minio:9000
  #       - MINIO_ACCESS_KEY=minio_access_key
  #       - MINIO_SECRET_KEY=minio_secret_key
  #       - MINIO_BUCKET_NAME=audio-files
  #     depends_on:
  #       - minio

  # volumes:
  #   postgres_data:
  #   minio_data:
